# Generated by Django 2.2.5 on 2019-12-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20191217_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='PREC',
            field=models.FloatField(choices=[(1.22, 'vl'), (1.09, 'l'), (1.0, 'n'), (0.93, 'h'), (0.86, 'vh'), (0.8, 'eh')], default=None, max_length=20),
        ),
    ]
