# Generated by Django 2.2.5 on 2019-12-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20191217_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='ACAP',
            field=models.FloatField(choices=[(1.42, 'vl'), (1.19, 'l'), (1.0, 'n'), (0.85, 'h'), (0.71, 'vh'), (1.0, 'eh')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='AEXP',
            field=models.FloatField(choices=[(1.22, 'vl'), (1.1, 'l'), (1.0, 'n'), (0.88, 'h'), (0.81, 'vh'), (1.0, 'eh')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='CPLX',
            field=models.FloatField(choices=[(0.73, 'vl'), (0.87, 'l'), (1.0, 'n'), (1.17, 'h'), (1.34, 'vh'), (1.74, 'eh')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='DATA',
            field=models.FloatField(choices=[(1.0, 'vl'), (0.9, 'l'), (1.0, 'n'), (1.14, 'h'), (1.28, 'vh'), (1.0, 'eh')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='DOCU',
            field=models.FloatField(choices=[(0.81, 'vl'), (0.91, 'l'), (1.0, 'n'), (1.11, 'h'), (1.23, 'vh'), (1.0, 'eh')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='FLEX',
            field=models.FloatField(choices=[(5.07, 'vl'), (4.05, 'l'), (3.04, 'n'), (2.03, 'h'), (1.01, 'vh'), (0.0, 'eh')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='LTEX',
            field=models.FloatField(choices=[(1.2, 'vl'), (1.09, 'l'), (1.0, 'n'), (0.91, 'h'), (0.84, 'vh'), (1.0, 'eh')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='PCAP',
            field=models.FloatField(choices=[(1.34, 'vl'), (1.15, 'l'), (1.0, 'n'), (0.88, 'h'), (0.76, 'vh'), (1.0, 'eh')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='PCON',
            field=models.FloatField(choices=[(1.29, 'vl'), (1.12, 'l'), (1.0, 'n'), (0.9, 'h'), (0.81, 'vh'), (1.0, 'eh')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='PEXP',
            field=models.FloatField(choices=[(1.19, 'vl'), (1.09, 'l'), (1.0, 'n'), (0.91, 'h'), (0.85, 'vh'), (1.0, 'eh')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='PMAT',
            field=models.FloatField(choices=[(7.8, 'vl'), (6.24, 'l'), (4.68, 'n'), (3.12, 'h'), (1.56, 'vh'), (0.0, 'eh')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='PREC',
            field=models.FloatField(choices=[(6.2, 'vl'), (4.96, 'l'), (3.72, 'n'), (2.48, 'h'), (1.24, 'vh'), (0.0, 'eh')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='PVOL',
            field=models.FloatField(choices=[(1.0, 'vl'), (0.87, 'l'), (1.0, 'n'), (1.15, 'h'), (1.3, 'vh'), (1.0, 'eh')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='RELY',
            field=models.FloatField(choices=[(0.82, 'vl'), (0.92, 'l'), (1.0, 'n'), (1.1, 'h'), (1.26, 'vh'), (1.0, 'eh')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='RESL',
            field=models.FloatField(choices=[(7.07, 'vl'), (5.65, 'l'), (4.24, 'n'), (2.83, 'h'), (1.41, 'vh'), (0.0, 'eh')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='RUSE',
            field=models.FloatField(choices=[(1.0, 'vl'), (0.95, 'l'), (1.0, 'n'), (1.07, 'h'), (1.15, 'vh'), (1.24, 'eh')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='SCED',
            field=models.FloatField(choices=[(1.43, 'vl'), (1.14, 'l'), (1.0, 'n'), (1.0, 'h'), (1.0, 'vh'), (1.0, 'eh')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='SITE',
            field=models.FloatField(choices=[(1.22, 'vl'), (1.09, 'l'), (1.0, 'n'), (0.93, 'h'), (0.86, 'vh'), (0.8, 'eh')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='STOR',
            field=models.FloatField(choices=[(1.0, 'vl'), (1.0, 'l'), (1.0, 'n'), (1.05, 'h'), (1.17, 'vh'), (1.46, 'eh')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='TEAM',
            field=models.FloatField(choices=[(7.8, 'vl'), (6.24, 'l'), (4.68, 'n'), (3.12, 'h'), (1.56, 'vh'), (0.0, 'eh')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='TIME',
            field=models.FloatField(choices=[(1.0, 'vl'), (1.0, 'l'), (1.0, 'n'), (1.11, 'h'), (1.29, 'vh'), (1.63, 'eh')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='TOOL',
            field=models.FloatField(choices=[(1.17, 'vl'), (1.09, 'l'), (1.0, 'n'), (0.9, 'h'), (0.78, 'vh'), (1.0, 'eh')], default=None, max_length=20),
        ),
    ]
