# Generated by Django 2.2.5 on 2019-12-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20191217_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='ACAP',
            field=models.FloatField(choices=[('vl', 1.42), ('l', 1.19), ('n', 1.0), ('h', 0.85), ('vh', 0.71), ('eh', 1.0)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='AEXP',
            field=models.FloatField(choices=[('vl', 1.22), ('l', 1.1), ('n', 1.0), ('h', 0.88), ('vh', 0.81), ('eh', 1.0)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='CPLX',
            field=models.FloatField(choices=[('vl', 0.73), ('l', 0.87), ('n', 1.0), ('h', 1.17), ('vh', 1.34), ('eh', 1.74)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='DATA',
            field=models.FloatField(choices=[('vl', 1.0), ('l', 0.9), ('n', 1.0), ('h', 1.14), ('vh', 1.28), ('eh', 1.0)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='DOCU',
            field=models.FloatField(choices=[('vl', 0.81), ('l', 0.91), ('n', 1.0), ('h', 1.11), ('vh', 1.23), ('eh', 1.0)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='FLEX',
            field=models.FloatField(choices=[('vl', 5.07), ('l', 4.05), ('n', 3.04), ('h', 2.03), ('vh', 1.01), ('eh', 0.0)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='LTEX',
            field=models.FloatField(choices=[('vl', 1.2), ('l', 1.09), ('n', 1.0), ('h', 0.91), ('vh', 0.84), ('eh', 1.0)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='PCAP',
            field=models.FloatField(choices=[('vl', 1.34), ('l', 1.15), ('n', 1.0), ('h', 0.88), ('vh', 0.76), ('eh', 1.0)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='PCON',
            field=models.FloatField(choices=[('vl', 1.29), ('l', 1.12), ('n', 1.0), ('h', 0.9), ('vh', 0.81), ('eh', 1.0)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='PEXP',
            field=models.FloatField(choices=[('vl', 1.19), ('l', 1.09), ('n', 1.0), ('h', 0.91), ('vh', 0.85), ('eh', 1.0)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='PMAT',
            field=models.FloatField(choices=[('vl', 7.8), ('l', 6.24), ('n', 4.68), ('h', 3.12), ('vh', 1.56), ('eh', 0.0)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='PREC',
            field=models.FloatField(choices=[('vl', 6.2), ('l', 4.96), ('n', 3.72), ('h', 2.48), ('vh', 1.24), ('eh', 0.0)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='PVOL',
            field=models.FloatField(choices=[('vl', 1.0), ('l', 0.87), ('n', 1.0), ('h', 1.15), ('vh', 1.3), ('eh', 1.0)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='RELY',
            field=models.FloatField(choices=[('vl', 0.82), ('l', 0.92), ('n', 1.0), ('h', 1.1), ('vh', 1.26), ('eh', 1.0)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='RESL',
            field=models.FloatField(choices=[('vl', 7.07), ('l', 5.65), ('n', 4.24), ('h', 2.83), ('vh', 1.41), ('eh', 0.0)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='RUSE',
            field=models.FloatField(choices=[('vl', 1.0), ('l', 0.95), ('n', 1.0), ('h', 1.07), ('vh', 1.15), ('eh', 1.24)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='SCED',
            field=models.FloatField(choices=[('vl', 1.43), ('l', 1.14), ('n', 1.0), ('h', 1.0), ('vh', 1.0), ('eh', 1.0)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='SITE',
            field=models.FloatField(choices=[('vl', 1.22), ('l', 1.09), ('n', 1.0), ('h', 0.93), ('vh', 0.86), ('eh', 0.8)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='STOR',
            field=models.FloatField(choices=[('vl', 1.0), ('l', 1.0), ('n', 1.0), ('h', 1.05), ('vh', 1.17), ('eh', 1.46)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='TEAM',
            field=models.FloatField(choices=[('vl', 7.8), ('l', 6.24), ('n', 4.68), ('h', 3.12), ('vh', 1.56), ('eh', 0.0)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='TIME',
            field=models.FloatField(choices=[('vl', 1.0), ('l', 1.0), ('n', 1.0), ('h', 1.11), ('vh', 1.29), ('eh', 1.63)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='TOOL',
            field=models.FloatField(choices=[('vl', 1.17), ('l', 1.09), ('n', 1.0), ('h', 0.9), ('vh', 0.78), ('eh', 1.0)], default=None, max_length=20),
        ),
    ]
