# Generated by Django 2.2.5 on 2019-12-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20191217_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='ACAP',
            field=models.CharField(choices=[('非常低', 1.42), ('低', 1.19), ('正常', 1.0), ('高', 0.85), ('非常高', 0.71), ('超高', 1.0)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='AEXP',
            field=models.CharField(choices=[('非常低', 1.22), ('低', 1.1), ('正常', 1.0), ('高', 0.88), ('非常高', 0.81), ('超高', 1.0)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='CPLX',
            field=models.CharField(choices=[('非常低', 0.73), ('低', 0.87), ('正常', 1.0), ('高', 1.17), ('非常高', 1.34), ('超高', 1.74)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='DATA',
            field=models.CharField(choices=[('非常低', 1.0), ('低', 0.9), ('正常', 1.0), ('高', 1.14), ('非常高', 1.28), ('超高', 1.0)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='DOCU',
            field=models.CharField(choices=[('非常低', 0.81), ('低', 0.91), ('正常', 1.0), ('高', 1.11), ('非常高', 1.23), ('超高', 1.0)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='FLEX',
            field=models.CharField(choices=[('非常低', 5.07), ('低', 4.05), ('正常', 3.04), ('高', 2.03), ('非常高', 1.01), ('超高', 0.0)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='LTEX',
            field=models.CharField(choices=[('非常低', 1.2), ('低', 1.09), ('正常', 1.0), ('高', 0.91), ('非常高', 0.84), ('超高', 1.0)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='PCAP',
            field=models.CharField(choices=[('非常低', 1.34), ('低', 1.15), ('正常', 1.0), ('高', 0.88), ('非常高', 0.76), ('超高', 1.0)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='PCON',
            field=models.CharField(choices=[('非常低', 1.29), ('低', 1.12), ('正常', 1.0), ('高', 0.9), ('非常高', 0.81), ('超高', 1.0)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='PEXP',
            field=models.CharField(choices=[('非常低', 1.19), ('低', 1.09), ('正常', 1.0), ('高', 0.91), ('非常高', 0.85), ('超高', 1.0)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='PMAT',
            field=models.CharField(choices=[('非常低', 7.8), ('低', 6.24), ('正常', 4.68), ('高', 3.12), ('非常高', 1.56), ('超高', 0.0)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='PREC',
            field=models.CharField(choices=[('非常低', 6.2), ('低', 4.96), ('正常', 3.72), ('高', 2.48), ('非常高', 1.24), ('超高', 0.0)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='PVOL',
            field=models.CharField(choices=[('非常低', 1.0), ('低', 0.87), ('正常', 1.0), ('高', 1.15), ('非常高', 1.3), ('超高', 1.0)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='RELY',
            field=models.CharField(choices=[('非常低', 0.82), ('低', 0.92), ('正常', 1.0), ('高', 1.1), ('非常高', 1.26), ('超高', 1.0)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='RESL',
            field=models.CharField(choices=[('非常低', 7.07), ('低', 5.65), ('正常', 4.24), ('高', 2.83), ('非常高', 1.41), ('超高', 0.0)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='RUSE',
            field=models.CharField(choices=[('非常低', 1.0), ('低', 0.95), ('正常', 1.0), ('高', 1.07), ('非常高', 1.15), ('超高', 1.24)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='SCED',
            field=models.CharField(choices=[('非常低', 1.43), ('低', 1.14), ('正常', 1.0), ('高', 1.0), ('非常高', 1.0), ('超高', 1.0)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='SITE',
            field=models.CharField(choices=[('非常低', 1.22), ('低', 1.09), ('正常', 1.0), ('高', 0.93), ('非常高', 0.86), ('超高', 0.8)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='STOR',
            field=models.CharField(choices=[('非常低', 1.0), ('低', 1.0), ('正常', 1.0), ('高', 1.05), ('非常高', 1.17), ('超高', 1.46)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='TEAM',
            field=models.CharField(choices=[('非常低', 7.8), ('低', 6.24), ('正常', 4.68), ('高', 3.12), ('非常高', 1.56), ('超高', 0.0)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='TIME',
            field=models.CharField(choices=[('非常低', 1.0), ('低', 1.0), ('正常', 1.0), ('高', 1.11), ('非常高', 1.29), ('超高', 1.63)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='TOOL',
            field=models.CharField(choices=[('非常低', 1.17), ('低', 1.09), ('正常', 1.0), ('高', 0.9), ('非常高', 0.78), ('超高', 1.0)], default=None, max_length=20),
        ),
    ]
